# Generated by Django 3.2.12 on 2022-04-19 20:23

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='name',
        ),
        migrations.AddField(
            model_name='mentee',
            name='goals',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), null=True, size=None),
        ),
        migrations.AddField(
            model_name='mentor',
            name='education',
            field=models.CharField(max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='mentor',
            name='mentee_limit',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='mentor',
            name='mentees',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=80), null=True, size=models.IntegerField(null=True)),
        ),
        migrations.AddField(
            model_name='mentor',
            name='mentorship_duration',
            field=models.DurationField(null=True),
        ),
        migrations.AddField(
            model_name='mentor',
            name='professional_experience',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='age',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='personal_interests',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='professional_interests',
            field=models.TextField(null=True),
        ),
    ]
