# Generated by Django 3.2.12 on 2022-04-02 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_login'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Login',
        ),
    ]
