# Generated by Django 3.2.12 on 2022-04-30 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_alter_mentee_mentor'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('mentee', 'Mentee'), ('mentor', 'Mentor')], max_length=80, null=True),
        ),
    ]
