# Generated by Django 3.2.12 on 2022-04-30 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_user_user_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='age',
        ),
        migrations.AddField(
            model_name='mentee',
            name='personal_interests',
            field=models.CharField(choices=[('Painting', 'Painting'), ('Music', 'Music'), ('Photogrpahy', 'Photography'), ('Reading', 'Reading'), ('Sports', 'Sports'), ('Cooking', 'Cooking')], max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='mentee',
            name='professional_interests',
            field=models.CharField(choices=[('Technical Interviews', 'Technical Interviews'), ('Web Development', 'Wed Development'), ('App Development', 'App Development'), ('Math', 'Math'), ('Computer Science', 'Computer Science'), ('Science', 'Science'), ('Engineering', 'Engineering')], max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='mentor',
            name='personal_interests',
            field=models.CharField(choices=[('Painting', 'Painting'), ('Music', 'Music'), ('Photogrpahy', 'Photography'), ('Reading', 'Reading'), ('Sports', 'Sports'), ('Cooking', 'Cooking')], max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='mentor',
            name='professional_interests',
            field=models.CharField(choices=[('Technical Interviews', 'Technical Interviews'), ('Web Development', 'Wed Development'), ('App Development', 'App Development'), ('Math', 'Math'), ('Computer Science', 'Computer Science'), ('Science', 'Science'), ('Engineering', 'Engineering')], max_length=80, null=True),
        ),
    ]
