# Generated by Django 3.2.12 on 2022-04-05 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_auto_20220405_0010'),
        ('profiles', '0003_delete_login'),
    ]

    operations = [
    ]
