# Generated by Django 3.2.12 on 2022-04-30 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_auto_20220430_1421'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_mentee',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_mentor',
        ),
    ]
